export const GENERATOR_AUTHORING_CLASSES = {
  root: "tm-generator-authoring",
  section: "tm-generator-authoring__section",
  sectionCard: "tm-generator-authoring__section-card",
  titleBlock: "tm-generator-authoring__title-block",
  title: "tm-generator-authoring__title",
  description: "tm-generator-authoring__description",
  fieldStack: "tm-generator-authoring__field-stack",
  fieldGrid: "tm-generator-authoring__field-grid",
  buttonGrid: "tm-generator-authoring__button-grid",
  control: "tm-generator-authoring__control",
  controlMono: "tm-generator-authoring__control tm-generator-authoring__control--mono",
  summaryCard: "tm-generator-authoring__summary-card",
  summaryRow: "tm-generator-authoring__summary-row",
  summaryLabel: "tm-generator-authoring__summary-label",
  summaryValue: "tm-generator-authoring__summary-value",
  summaryMono: "tm-generator-authoring__summary-mono",
  metricGrid: "tm-generator-authoring__metric-grid",
  metricCard: "tm-generator-authoring__metric-card",
  metricValue: "tm-generator-authoring__metric-value",
  cardList: "tm-generator-authoring__card-list",
} as const;
