export default {
  projectRoot: '.',
  files: {
    backlog: './backlog.md',
    inbox: './backlog-inbox.md',
    taskSpecsDir: './backlog/tasks',
    followups: './.backlog-runner/followups.jsonl',
    stop: './backlog-stop',
    patterns: './scripts/backlog/patterns.md',
    progress: './scripts/backlog/progress.txt',
    stateDb: './.backlog-runner/state.sqlite',
    models: './scripts/backlog/models.json',
    runnerLogDir: './.backlog-runner/logs',
    runtimeDir: './.backlog-runner',
  },
  prompts: {
    agent: './scripts/backlog/agent.md',
    product: './scripts/backlog/product-pass.md',
    ux: './scripts/backlog/ux-pass.md',
    code: './scripts/backlog/code-pass.md',
  },
  validationCommand: 'bash scripts/backlog/validate.sh',
  validationProfiles: {
    repo: 'bash scripts/backlog/validate.sh',
    core: 'pnpm --filter @tokenmanager/core build',
    server: 'pnpm --filter @tokenmanager/server build',
    plugin: 'pnpm preview:build',
    backlog: 'pnpm --filter @tokenmanager/backlog-runner exec vitest run',
  },
  defaults: {
    tool: 'claude',
    model: '',
    passModel: '',
    passes: true,
    passFrequency: 10,
    worktrees: true,
  },
  passes: {
    product: { offset: 3 },
    ux: { offset: 7 },
    code: { offset: 0 },
  },
};
