/**
 * ValueCell — per-mode value display for the token list.
 *
 * Display-only: renders a type-aware preview (swatch, text, alias arrow) and
 * emits a request upward when the user clicks to edit, or clicks "+" on a
 * missing mode value. The quick editor popover is mounted by the parent row,
 * not by the cell itself, so every token type shares one editing surface.
 */
import { useRef } from "react";
import type { CSSProperties } from "react";
import { AlertTriangle, Wand2 } from "lucide-react";
import type { TokenMapEntry } from "../../../shared/types";
import { extractAliasPath, isAlias } from "../../../shared/resolveAlias";
import { formatValue } from "../tokenListUtils";
import { ValuePreview } from "../ValuePreview";
import { QUICK_EDITABLE_TYPES } from "../tokenListTypes";
import { getValueCellPresentation } from "./valueCellPresentation";

export interface QuickEditRequest {
  anchor: DOMRect;
  optionName: string;
  collectionId: string;
  targetCollectionId: string | null;
  currentValue: TokenMapEntry | undefined;
}

interface ValueCellProps {
  tokenType: string | undefined;
  currentValue: TokenMapEntry | undefined;
  targetCollectionId: string | null;
  collectionId: string;
  optionName: string;
  /** When set, the row is a generator output — renders a derivation glyph. */
  derivedGeneratorName?: string | null;
  /** Called when the user clicks the cell to edit — parent opens the quick editor popover. */
  onRequestQuickEdit?: (req: QuickEditRequest) => void;
  /** Fallback when quick editing isn't supported for this type. */
  onEdit?: () => void;
}

export function ValueCell({
  tokenType,
  currentValue: value,
  targetCollectionId,
  collectionId,
  optionName,
  derivedGeneratorName,
  onRequestQuickEdit,
  onEdit,
}: ValueCellProps) {
  const cellRef = useRef<HTMLDivElement>(null);

  const isBrokenAlias = isAlias(value?.$value);
  const resolvedAliasPath = value?.reference && !isBrokenAlias
    ? extractAliasPath(value.reference)
    : null;
  const isResolvedAlias = resolvedAliasPath != null;
  const canQuickEdit =
    !!tokenType &&
    (QUICK_EDITABLE_TYPES.has(tokenType) || isBrokenAlias) &&
    !!targetCollectionId &&
    !!onRequestQuickEdit;
  const canCreate = !value && !!tokenType && !!targetCollectionId && !!onRequestQuickEdit;

  const displayVal = value ? formatValue(value.$type, value.$value) : "—";
  const presentation = value
    ? getValueCellPresentation(value)
    : null;

  const openQuickEdit = () => {
    if (!onRequestQuickEdit) return;
    const rect = cellRef.current?.getBoundingClientRect();
    if (!rect) return;
    onRequestQuickEdit({
      anchor: rect,
      optionName,
      collectionId,
      targetCollectionId,
      currentValue: value,
    });
  };

  const brokenAliasTint = isBrokenAlias
    ? "bg-[var(--color-figma-warning,#f59e0b)]/5"
    : "";
  const emptyUneditableTint = !value && !canCreate
    ? "bg-[var(--color-figma-warning,#f59e0b)]/5"
    : "";
  const wrapperClass = `min-w-0 shrink-0 px-1.5 flex items-center gap-1.5 border-l border-[var(--color-figma-border)] h-full ${brokenAliasTint} ${emptyUneditableTint}`;

  const derivedMarker = derivedGeneratorName ? (
    <span
      className="shrink-0 text-[var(--color-figma-text-tertiary)]"
      title={`Generated by ${derivedGeneratorName}`}
      aria-label={`Generated by ${derivedGeneratorName}`}
    >
      <Wand2 size={10} strokeWidth={2} aria-hidden />
    </span>
  ) : null;
  const interactiveTextClass = canQuickEdit
    ? "cursor-pointer hover:text-[var(--color-figma-text)]"
    : "";

  const renderValueText = (
    primary: string,
    secondary?: string,
    options?: {
      primaryMonospace?: boolean;
      secondaryMonospace?: boolean;
      primaryClassName?: string;
      secondaryClassName?: string;
      primaryStyle?: CSSProperties;
      secondaryStyle?: CSSProperties;
    },
  ) => (
    <div
      className={`min-w-0 flex-1 ${interactiveTextClass}`}
      onClick={
        canQuickEdit
          ? (e) => {
              e.stopPropagation();
              openQuickEdit();
            }
          : undefined
      }
    >
      <div
        className={`truncate text-[11px] leading-[1.08] ${
          options?.primaryMonospace ? "font-mono" : ""
        } ${options?.primaryClassName ?? "text-[var(--color-figma-text)]"}`}
        style={options?.primaryStyle}
      >
        {primary}
      </div>
      {secondary ? (
        <div
          className={`truncate text-[10px] leading-[1.08] ${
            options?.secondaryMonospace ? "font-mono" : ""
          } ${
            options?.secondaryClassName ??
            "text-[var(--color-figma-text-tertiary)]"
          }`}
          style={options?.secondaryStyle}
        >
          {secondary}
        </div>
      ) : null}
    </div>
  );

  return (
    <div
      ref={cellRef}
      className={wrapperClass}
      title={`${optionName}: ${displayVal}${targetCollectionId ? `\nSet: ${targetCollectionId}` : ""}`}
    >
      {!value ? (
        canCreate ? (
          <button
            type="button"
            className="text-body text-[var(--color-figma-text-tertiary)] cursor-pointer hover:text-[var(--color-figma-accent)] hover:bg-[var(--color-figma-accent)]/10 rounded px-1 py-px transition-colors"
            onClick={(e) => {
              e.stopPropagation();
              openQuickEdit();
            }}
            aria-label="Add mode value"
          >
            +
          </button>
        ) : onEdit ? (
          <button
            type="button"
            className="text-body text-[var(--color-figma-text-tertiary)] cursor-pointer hover:text-[var(--color-figma-accent)] hover:bg-[var(--color-figma-accent)]/10 rounded px-1 py-px transition-colors"
            onClick={(e) => {
              e.stopPropagation();
              onEdit();
            }}
            aria-label="Add mode value"
          >
            +
          </button>
        ) : (
          <span className="text-body text-[var(--color-figma-text-tertiary)]">
            —
          </span>
        )
      ) : isBrokenAlias ? (
        <>
          {derivedMarker}
          <span
            className="shrink-0 text-[var(--color-figma-warning,#f59e0b)]"
            aria-label="Broken reference"
          >
            <AlertTriangle size={10} strokeWidth={2} aria-hidden />
          </span>
          {renderValueText(displayVal, "Reference not found", {
            primaryMonospace: true,
            primaryClassName:
              "font-mono italic text-[var(--color-figma-warning,#f59e0b)]",
            secondaryClassName: "text-[var(--color-figma-warning,#f59e0b)]/80",
          })}
        </>
      ) : isResolvedAlias ? (
        <>
          {derivedMarker}
          <span className="shrink-0">
            <ValuePreview type={value.$type} value={value.$value} size={16} />
          </span>
          {renderValueText(
            presentation?.secondary
              ? `${presentation.primary} · ${presentation.secondary}`
              : (presentation?.primary ?? displayVal),
            resolvedAliasPath ?? undefined,
            {
              primaryMonospace:
                Boolean(presentation?.primaryMonospace) &&
                !presentation?.secondary,
              secondaryMonospace: true,
              secondaryClassName: "text-[var(--color-figma-text-secondary)]",
              primaryStyle: presentation?.primaryStyle,
              secondaryStyle: presentation?.secondaryStyle,
            },
          )}
        </>
      ) : (
        <>
          {derivedMarker}
          <span className="shrink-0">
            <ValuePreview type={value.$type} value={value.$value} size={16} />
          </span>
          {renderValueText(
            presentation?.primary ?? displayVal,
            presentation?.secondary,
            {
              primaryMonospace: presentation?.primaryMonospace,
              secondaryMonospace: presentation?.secondaryMonospace,
              primaryStyle: presentation?.primaryStyle,
              secondaryStyle: presentation?.secondaryStyle,
            },
          )}
        </>
      )}
    </div>
  );
}
