import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { inspectBacklogState } from '../context.js';
import { normalizeBacklogRunnerConfig } from '../config.js';

const tempDirs: string[] = [];

async function makeConfig(root: string) {
  return normalizeBacklogRunnerConfig(
    {
      files: {
        backlog: './backlog.md',
        candidateQueue: './backlog/inbox.jsonl',
        taskSpecsDir: './backlog/tasks',
        stop: './backlog-stop',
        patterns: './scripts/backlog/patterns.md',
        progress: './scripts/backlog/progress.txt',
      },
      prompts: {
        agent: './scripts/backlog/agent.md',
        planner: './scripts/backlog/planner.md',
        product: './scripts/backlog/product.md',
        interface: './scripts/backlog/interface.md',
        ux: './scripts/backlog/ux.md',
        code: './scripts/backlog/code.md',
      },
      validationCommand: 'true',
      runners: {
        taskUi: { tool: 'claude', model: 'opus' },
        taskCode: { tool: 'codex', model: 'default' },
        planner: { tool: 'codex', model: 'default' },
        product: { tool: 'codex', model: 'default' },
        interface: { tool: 'claude', model: 'sonnet' },
        ux: { tool: 'codex', model: 'default' },
        code: { tool: 'codex', model: 'default' },
      },
    },
    path.join(root, 'backlog.config.mjs'),
  );
}

async function makeFixture(backlogContent = '', taskFiles: Record<string, string> = {}) {
  const root = await mkdtemp(path.join(tmpdir(), 'backlog-context-test-'));
  tempDirs.push(root);
  await mkdir(path.join(root, 'scripts/backlog'), { recursive: true });
  await mkdir(path.join(root, 'backlog/tasks'), { recursive: true });
  await mkdir(path.join(root, 'backlog'), { recursive: true });
  await writeFile(path.join(root, 'backlog.md'), backlogContent, 'utf8');
  await writeFile(path.join(root, 'backlog/inbox.jsonl'), '', 'utf8');
  await writeFile(path.join(root, 'backlog-stop'), '', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/patterns.md'), '# Patterns\n', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/progress.txt'), '# Progress\n', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/agent.md'), 'agent', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/planner.md'), 'planner', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/product.md'), 'product', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/ux.md'), 'ux', 'utf8');
  await writeFile(path.join(root, 'scripts/backlog/code.md'), 'code', 'utf8');
  for (const [name, content] of Object.entries(taskFiles)) {
    const filePath = path.join(root, 'backlog/tasks', name);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content, 'utf8');
  }
  return makeConfig(root);
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map(dir => rm(dir, { recursive: true, force: true })));
});

describe('context backlog inspection', () => {
  it('reports zero task specs when directory is empty', async () => {
    const config = await makeFixture();

    await expect(inspectBacklogState(config)).resolves.toMatchObject({
      generatedReport: false,
      hasLegacyTasks: false,
      taskSpecCount: 0,
      duplicateTaskIds: [],
    });
  });

  it('detects generated backlog reports and top-level task specs', async () => {
    const config = await makeFixture(
      '# UX Improvement Backlog\n\n<!-- This file is generated by packages/backlog-runner from backlog/tasks/**/*.yaml. -->\n',
      {
      'task-a.yaml': 'id: task-a\ntitle: Task A\npriority: normal\ntask_kind: implementation\nexecution_domain: code_logic\ndepends_on: []\ntouch_paths:\n  - feature.txt\ncapabilities: []\nvalidation_profile: repo\nstatus_notes:\n  - Seeded\nstate: ready\nacceptance_criteria:\n  - Task A\nsource: manual\ncreated_at: 2026-04-08T00:00:00.000Z\nupdated_at: 2026-04-08T00:00:00.000Z\n',
      },
    );

    await expect(inspectBacklogState(config)).resolves.toMatchObject({
      generatedReport: true,
      hasLegacyTasks: false,
      taskSpecCount: 1,
      duplicateTaskIds: [],
    });
  });

  it('counts nested archived task specs and detects duplicate ids', async () => {
    const config = await makeFixture(
      '# Backlog\n\n- [ ] Legacy task\n',
      {
      'done/task-a.yaml': 'id: task-a\ntitle: Task A\npriority: normal\ntask_kind: implementation\nexecution_domain: code_logic\ndepends_on: []\ntouch_paths:\n  - feature.txt\ncapabilities: []\nvalidation_profile: repo\nstatus_notes:\n  - Seeded\nstate: done\nacceptance_criteria:\n  - Task A\nsource: manual\ncreated_at: 2026-04-08T00:00:00.000Z\nupdated_at: 2026-04-08T00:00:00.000Z\n',
      'task-a.yaml': 'id: task-a\ntitle: Task A duplicate\npriority: normal\ntask_kind: implementation\nexecution_domain: code_logic\ndepends_on: []\ntouch_paths:\n  - feature.txt\ncapabilities: []\nvalidation_profile: repo\nstatus_notes:\n  - Seeded\nstate: ready\nacceptance_criteria:\n  - Task A duplicate\nsource: manual\ncreated_at: 2026-04-08T00:00:00.000Z\nupdated_at: 2026-04-08T00:01:00.000Z\n',
      },
    );

    await expect(inspectBacklogState(config)).resolves.toMatchObject({
      generatedReport: false,
      hasLegacyTasks: true,
      taskSpecCount: 2,
      duplicateTaskIds: ['task-a'],
    });
  });
});
